var stp = [
    ["INCOTERMS 2010 - opste", "1. skup jedinstvenih pravila, sistematizovanih i oznacenih skracenicama koje predstavljaju uobicajene uslove po kojima se odvija medj trg. \n 2. cilj je stvaranje standardnog tumacenja ugovorneih trg termina od strane svih ucesnika. \n 3. postize se : \n \t 1. eliminisu se nepsorazumu razlictih tumacenja \n \t 2. eliminisu sporovi \n \t 3. eliminise zastoj i ubrzava se medj trg \n Odomacen je naziv pariteti/transportne klauzule"],
    ["INOTERMS 2010 - istorija", "'36 - 11, \n 53, 67, 76, 90, 90, 2000 - 13, 2010 \n 2010 - moze u unutrasnjoj trg, ne moze nematerijalizovana dobra/int svojina/usluge"],
    ["INCOTERMS 2010 - sta definisu", "prava i obaveze kupca i prodavca, jedan ili vise modaliteta trasnporta, \n 1. koji vid prevoza, \n 2. ko ima obavezu prevoza/tr prevoza \n 3. gde ce biti izvrsena isporuka \n 4. ko ima obavezu da osiguraa robu/tr osiguranja \n 5. ko vrsi izvozno/uvozno carinjenje \n 6. kada se prenosi vl i rizik nad robom. \n troskovi pakovanja padaju na teret izvoznika, dok tr pregleda robe pre isporuke padaju na teret kupca"],
    ["INCOTERMS 2010 - klauzule", "EXW - minimum obaveze za prodava. Stavlja robu na raspolaganje kupcu, bez obaveze njenog utovaranja. Sve ostalo, prevoz osiugranje, izv/uv car vrsi kupac \n F - oslobadja prodavca od ug i placanja prevoza i osguranja robe. pr stavlja robu na raspolaganje i jedino ima obavezu utovara kada su prostorije prodavca naglasene kao mesto otrpeme. Izvozno carinjenje vrsi prodavac \n C - prodavac ugovara prevoz, CIF i CIP podrazumevaju za prodavca pored obaveze prevoza i obavezu osnovnog osiguranja robe do naznacenog mesta. Pr vrsi izv car \n D - prodavac ima obavezu prevoza robe i placanja troskova vozaine do naznaceong mesta, ali bez obaveze osiguranja. Prodavac ima obavezu placanja izv dazdbina i izv car. Uvozno car vrsi kupac. *DDP je izuzetak posto je njom predvidjen maksimu obaveza za prodavca."],
    ["INCOTERMS 2010 - podela na ospte i na za pomorski i recni", "(FAS, FOB, CFR, CIF), koja je najbolja - nema pravila. \n 11 razlicitih klauzula daju 11 razlictih cena. Neke detalje izv i uvoznik treba ipak da preciziraju da ne bi doslo do nesporazuma."],
    ["Fakture - izvozne fakture", "osnovni dokument u spt poslu. To je racun za robu koja se izvozi. Ona sadrzi sledece elemente: \n 1. ime i adresu izv \n 2. ime i adresu kupca \n 3. broj fakutre \n 4. broj porudzbine ili br ug \n 5. naziv robe, jedinicnu cenu i ukupnu cenu, \n 6. INCOTERMS klauzulu \n 7. tarifni br \n 8. neto i bruto tezinu \n 9. iznos snizenja cene \n //// \n za kupca je znacajan dokument kad roba prispe i potrebno je izvrsiti uvozno carinjenje. izvoznik mora fakutru da prilagodi i pripremi u skladu sa zahtevima kupca i njegovih carinskih organa i to kada od kupca dobije inof o uv car i nacinu transporta i osiguranja. Preporucuje se da se izda na jeziku zemlje uvoza ili na eng. na bazi vr robe u fakutru se odredjuje car osnovica i car vrednost. Znacajna je jos i zbog - dok naplate, pribavljanja dozvola uvoza i izvoza i utrvrdj trans tr" ],
    ["Fakture - proforma", "slicna izvoznoj, podaci su isti s tim sto cena u njoj nije konacna pa se ne koristi za car obracune. Daje je izvoznik na zahtev uv kako bi on realizova odredjene poslove na osnovu nje. Koristi se kod robe koja se privremeno izvoi/uv ili salje agentu na konsignaciju. Ukoliko se preda i dokaz o stvarno placenoj ceni moze se koristi pri carinjenju"],
    ["Fakture - privremena faktura", "Podaci istii kao i kod izvozne ali je cena u njoj privremena pa je i carinjenje privremeno te se stoga javlja povrcaja ili naplata razlike car dazbina. Koristi se kod uvoza robe kod koje se kvantitativno ili kvalitativno preuzimanje vrsi nakon isporkue"],
    ["Fakutre - gratis faktura", "daje je izvoznk za robu koja se isporucuje bez placanja protivvrednosti. Ta posiljka nije pracena placanjem ali podleze carini pa se mora uzeti cena u obzir i ne sme se staviti manja od realne. zove se jos i carinska faktura."],
    ["Fakture - konzularna faktura", "izdaje je diplomatsko predstavnistvo zemlje uvoza u zemlji izvoa na zahtev uvoznika koji podnosi izvoznik. Mora biti na jeziku zemlje uvoza i overava je konzulat zemlje uvoza sa sedistem u zemlji izvoza. \n Ovim se zemlja uvoza osigurava da izvoznik ne fakturise fiktivne vec realne cene i da ne vrsi reeksport. Odnosno ona potvrdjuje realnu vrednost robe i pruza uverenje o poreklu robe. Sad se umesto nje koristi EUROFORM, gde carina odredjuje carinksu osnovicu ukoliko sumnja u realnu vr robe"]
]